alter table PFA_PROJECT_ASSIGNMENT add constraint FK_PFA_PROJECT_ASSIGNMENT_ON_PROJECT foreign key (PROJECT_ID) references PFA_PROJECT(ID);
alter table PFA_PROJECT_ASSIGNMENT add constraint FK_PFA_PROJECT_ASSIGNMENT_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID);
create index IDX_PFA_PROJECT_ASSIGNMENT_ON_PROJECT on PFA_PROJECT_ASSIGNMENT (PROJECT_ID);
create index IDX_PFA_PROJECT_ASSIGNMENT_ON_ACCOUNT on PFA_PROJECT_ASSIGNMENT (ACCOUNT_ID);
