alter table PFA_COUNTRY_SETTING add constraint FK_PFA_COUNTRY_SETTING_ON_COUNTRY foreign key (COUNTRY_ID) references COUNTRY_COUNTRY(ID);
create index IDX_PFA_COUNTRY_SETTING_ON_COUNTRY on PFA_COUNTRY_SETTING (COUNTRY_ID);
