-- begin PFA_ACTIVITY
alter table PFA_ACTIVITY add constraint FK_PFA_ACTIVITY_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID)^
create index IDX_PFA_ACTIVITY_ON_ACCOUNT on PFA_ACTIVITY (ACCOUNT_ID)^
-- end PFA_ACTIVITY
-- begin PFA_ACTIVITY_DETAIL
alter table PFA_ACTIVITY_DETAIL add constraint FK_PFA_ACTIVITY_DETAIL_ON_ACTIVITY foreign key (ACTIVITY_ID) references PFA_ACTIVITY(ID)^
create index IDX_PFA_ACTIVITY_DETAIL_ON_ACTIVITY on PFA_ACTIVITY_DETAIL (ACTIVITY_ID)^
-- end PFA_ACTIVITY_DETAIL
