-- begin PFA_ACTIVITY
alter table PFA_ACTIVITY add constraint FK_PFA_ACTIVITY_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID)^
create index IDX_PFA_ACTIVITY_ON_ACCOUNT on PFA_ACTIVITY (ACCOUNT_ID)^
-- end PFA_ACTIVITY
-- begin PFA_ACTIVITY_DETAIL
alter table PFA_ACTIVITY_DETAIL add constraint FK_PFA_ACTIVITY_DETAIL_ON_ANALYTIC foreign key (ANALYTIC_ID) references PFA_ANALYTIC_SET(ID)^
alter table PFA_ACTIVITY_DETAIL add constraint FK_PFA_ACTIVITY_DETAIL_ON_ACTIVITY foreign key (ACTIVITY_ID) references PFA_ACTIVITY(ID)^
create index IDX_PFA_ACTIVITY_DETAIL_ON_ANALYTIC on PFA_ACTIVITY_DETAIL (ANALYTIC_ID)^
create index IDX_PFA_ACTIVITY_DETAIL_ON_ACTIVITY on PFA_ACTIVITY_DETAIL (ACTIVITY_ID)^
-- end PFA_ACTIVITY_DETAIL
-- begin PFA_PRICE_LIST
alter table PFA_PRICE_LIST add constraint FK_PFA_PRICE_LIST_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID)^
create index IDX_PFA_PRICE_LIST_ON_ACCOUNT on PFA_PRICE_LIST (ACCOUNT_ID)^
-- end PFA_PRICE_LIST
-- begin PFA_PRICE_LIST_DETAIL
alter table PFA_PRICE_LIST_DETAIL add constraint FK_PFA_PRICE_LIST_DETAIL_ON_PRICE_LIST foreign key (PRICE_LIST_ID) references PFA_PRICE_LIST(ID)^
alter table PFA_PRICE_LIST_DETAIL add constraint FK_PFA_PRICE_LIST_DETAIL_ON_ANALYTIC foreign key (ANALYTIC_ID) references PFA_ANALYTIC_SET(ID)^
alter table PFA_PRICE_LIST_DETAIL add constraint FK_PFA_PRICE_LIST_DETAIL_ON_REVENUE_TYPE foreign key (REVENUE_TYPE_ID) references PFA_REVENUE_TYPE(ID)^
create index IDX_PFA_PRICE_LIST_DETAIL_ON_PRICE_LIST on PFA_PRICE_LIST_DETAIL (PRICE_LIST_ID)^
create index IDX_PFA_PRICE_LIST_DETAIL_ON_ANALYTIC on PFA_PRICE_LIST_DETAIL (ANALYTIC_ID)^
create index IDX_PFA_PRICE_LIST_DETAIL_ON_REVENUE_TYPE on PFA_PRICE_LIST_DETAIL (REVENUE_TYPE_ID)^
-- end PFA_PRICE_LIST_DETAIL
-- begin PFA_ACCOUNT
alter table PFA_ACCOUNT add constraint FK_PFA_ACCOUNT_ON_PARENT foreign key (PARENT_ID) references PFA_ACCOUNT(ID)^
alter table PFA_ACCOUNT add constraint FK_PFA_ACCOUNT_ON_ACTUAL_REVISION foreign key (ACTUAL_REVISION_ID) references PFA_ACCOUNT_REVISION(ID)^
alter table PFA_ACCOUNT add constraint FK_PFA_ACCOUNT_ON_ACTUAL_MARKET_DETAIL foreign key (ACTUAL_MARKET_DETAIL_ID) references PFA_MARKET_DATA(ID)^
create index IDX_PFA_ACCOUNT_ON_PARENT on PFA_ACCOUNT (PARENT_ID)^
create index IDX_PFA_ACCOUNT_ON_ACTUAL_REVISION on PFA_ACCOUNT (ACTUAL_REVISION_ID)^
create index IDX_PFA_ACCOUNT_ON_ACTUAL_MARKET_DETAIL on PFA_ACCOUNT (ACTUAL_MARKET_DETAIL_ID)^
-- end PFA_ACCOUNT
-- begin PFA_ACCOUNT_REVISION
alter table PFA_ACCOUNT_REVISION add constraint FK_PFA_ACCOUNT_REVISION_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID)^
alter table PFA_ACCOUNT_REVISION add constraint FK_PFA_ACCOUNT_REVISION_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID)^
create index IDX_PFA_ACCOUNT_REVISION_ON_MANAGER on PFA_ACCOUNT_REVISION (MANAGER_ID)^
create index IDX_PFA_ACCOUNT_REVISION_ON_ACCOUNT on PFA_ACCOUNT_REVISION (ACCOUNT_ID)^
-- end PFA_ACCOUNT_REVISION
-- begin PFA_MARKET_DATA
alter table PFA_MARKET_DATA add constraint FK_PFA_MARKET_DATA_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID)^
create index IDX_PFA_MARKET_DATA_ON_ACCOUNT on PFA_MARKET_DATA (ACCOUNT_ID)^
-- end PFA_MARKET_DATA
-- begin PFA_EQUIPMENT_TYPE
alter table PFA_EQUIPMENT_TYPE add constraint FK_PFA_EQUIPMENT_TYPE_ON_CATEGORY foreign key (CATEGORY_ID) references PFA_EQUIPMENT_CATEGORY(ID)^
alter table PFA_EQUIPMENT_TYPE add constraint FK_PFA_EQUIPMENT_TYPE_ON_REVENUE_TYPE foreign key (REVENUE_TYPE_ID) references PFA_REVENUE_TYPE(ID)^
create index IDX_PFA_EQUIPMENT_TYPE_ON_CATEGORY on PFA_EQUIPMENT_TYPE (CATEGORY_ID)^
create index IDX_PFA_EQUIPMENT_TYPE_ON_REVENUE_TYPE on PFA_EQUIPMENT_TYPE (REVENUE_TYPE_ID)^
-- end PFA_EQUIPMENT_TYPE
-- begin PFA_SYSTEM_DETAIL
alter table PFA_SYSTEM_DETAIL add constraint FK_PFA_SYSTEM_DETAIL_ON_EQUIPMENT_TYPE foreign key (EQUIPMENT_TYPE_ID) references PFA_EQUIPMENT_TYPE(ID)^
alter table PFA_SYSTEM_DETAIL add constraint FK_PFA_SYSTEM_DETAIL_ON_SYSTEM foreign key (SYSTEM_ID) references PFA_SYSTEM_STD(ID)^
create index IDX_PFA_SYSTEM_DETAIL_ON_EQUIPMENT_TYPE on PFA_SYSTEM_DETAIL (EQUIPMENT_TYPE_ID)^
create index IDX_PFA_SYSTEM_DETAIL_ON_SYSTEM on PFA_SYSTEM_DETAIL (SYSTEM_ID)^
-- end PFA_SYSTEM_DETAIL
