version: 15
jobs:
- name: Test 0
  steps:
  - !CheckoutStep
    name: Checkout 1
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Setup proxy for gradle
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - cat >> gradle.properties <<EOL
      - systemProp.http.proxyHost=172.17.16.202
      - systemProp.http.proxyPort=3128
      - systemProp.https.proxyHost=172.17.16.202
      - systemProp.https.proxyPort=3128
      - EOL
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Trying to build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - ./gradlew clean build
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
