alter table PFA_APPLICATION_DATA add constraint FK_PFA_APPLICATION_DATA_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID);
create index IDX_PFA_APPLICATION_DATA_ON_ACCOUNT on PFA_APPLICATION_DATA (ACCOUNT_ID);
