alter table PFA_SYSTEM_DETAIL add constraint FK_PFA_SYSTEM_DETAIL_ON_EQUIPMENT_TYPE foreign key (EQUIPMENT_TYPE_ID) references PFA_EQUIPMENT_TYPE(ID);
alter table PFA_SYSTEM_DETAIL add constraint FK_PFA_SYSTEM_DETAIL_ON_SYSTEM foreign key (SYSTEM_ID) references PFA_SYSTEM_STD(ID);
create index IDX_PFA_SYSTEM_DETAIL_ON_EQUIPMENT_TYPE on PFA_SYSTEM_DETAIL (EQUIPMENT_TYPE_ID);
create index IDX_PFA_SYSTEM_DETAIL_ON_SYSTEM on PFA_SYSTEM_DETAIL (SYSTEM_ID);
