alter table PFA_ACCOUNT add constraint FK_PFA_ACCOUNT_ON_ACTUAL_APP_DETAIL foreign key (ACTUAL_APP_DETAIL_ID) references PFA_APPLICATION_DATA(ID);
create index IDX_PFA_ACCOUNT_ON_ACTUAL_APP_DETAIL on PFA_ACCOUNT (ACTUAL_APP_DETAIL_ID);
