alter table PFA_SYSTEM_ALLOCATION add constraint FK_PFA_SYSTEM_ALLOCATION_ON_APPLICATION_DATA foreign key (APPLICATION_DATA_ID) references PFA_APPLICATION_DATA(ID);
alter table PFA_SYSTEM_ALLOCATION add constraint FK_PFA_SYSTEM_ALLOCATION_ON_SYSTEM foreign key (SYSTEM_ID) references PFA_SYSTEM_STD(ID);
create index IDX_PFA_SYSTEM_ALLOCATION_ON_APPLICATION_DATA on PFA_SYSTEM_ALLOCATION (APPLICATION_DATA_ID);
create index IDX_PFA_SYSTEM_ALLOCATION_ON_SYSTEM on PFA_SYSTEM_ALLOCATION (SYSTEM_ID);
