alter table PFA_EQUIPMENT_TYPE add constraint FK_PFA_EQUIPMENT_TYPE_ON_CATEGORY foreign key (CATEGORY_ID) references PFA_EQUIPMENT_CATEGORY(ID);
create index IDX_PFA_EQUIPMENT_TYPE_ON_CATEGORY on PFA_EQUIPMENT_TYPE (CATEGORY_ID);
