alter table PFA_EQUIPMENT_TYPE add constraint FK_PFA_EQUIPMENT_TYPE_ON_REVENUE_TYPE foreign key (REVENUE_TYPE_ID) references PFA_REVENUE_TYPE(ID);
create index IDX_PFA_EQUIPMENT_TYPE_ON_REVENUE_TYPE on PFA_EQUIPMENT_TYPE (REVENUE_TYPE_ID);
