alter table PFA_SYSTEM_DETAIL add constraint FK_PFA_SYSTEM_DETAIL_ON_PART_NUMBER foreign key (PART_NUMBER_ID) references PN_PART(ID);
create index IDX_PFA_SYSTEM_DETAIL_ON_PART_NUMBER on PFA_SYSTEM_DETAIL (PART_NUMBER_ID);
