alter table PFA_SUPPLEMENTARY add constraint FK_PFA_SUPPLEMENTARY_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID);
create index IDX_PFA_SUPPLEMENTARY_ON_ACCOUNT on PFA_SUPPLEMENTARY (ACCOUNT_ID);
