CREATE OR ALTER VIEW SETTING_ANALYTIC_ORDER_vw as
SELECT PCSAD.ANALYTIC_SET_ID,
       PCS.COUNTRY_ID,
       PCSAD.ORDER_
FROM PFA_COUNTRY_SETTING PCS
         JOIN PFA_COUNTRY_SETTING_ANALYTIC_DETAIL PCSAD ON PCS.ID = PCSAD.COUNTRY_SETTING_ID