CREATE OR ALTER VIEW REVENUE_CALC_RULES AS
SELECT PCS.COUNTRY_ID,
       PCSRT.REVENUE_TYPE_ID,
       CSRTASL.ANALYTIC_SET_ID,
       dbo.getAnalyticTitle(JOB_TYPE, WELL_EQUIP, WELL_TAG) AS ANALYTIC_TITLE

FROM PFA_COUNTRY_SETTING_REVENUE_TYPE_ANALYTIC_SET_LINK CSRTASL
         JOIN PFA_ANALYTIC_SET PAS on PAS.ID = CSRTASL.ANALYTIC_SET_ID
         JOIN PFA_COUNTRY_SETTING_REVENUE_TYPE PCSRT on CSRTASL.COUNTRY_SETTING_REVENUE_TYPE_ID = PCSRT.ID
         JOIN PFA_COUNTRY_SETTING PCS on PCSRT.COUNTRY_SETTING_ID = PCS.ID^