exec sp_rename 'PFA_PRICE_LIST.RENTAL_RATE', 'RENTAL_RATE__U97920', 'COLUMN' ^
exec sp_rename 'PFA_PRICE_LIST.WELL_CHECK', 'WELL_CHECK__U20481', 'COLUMN' ^
exec sp_rename 'PFA_PRICE_LIST.REMOTE_MONITORING', 'REMOTE_MONITORING__U99155', 'COLUMN' ^
