UPDATE PFA_COUNTRY_SETTING_UTILIZATION_VALUE_TYPE
SET PFA_COUNTRY_SETTING_UTILIZATION_VALUE_TYPE.REMAP_SCRIPT =
        ALLOC_REMAP.REMAP_SCRIPT
FROM (
         SELECT UTILIZATION_VALUE_TYPE_ID, REMAP_SCRIPT
         FROM PFA_COUNTRY_SETTING_SYSTEM_ALLOCATION_REMAP ) ALLOC_REMAP
WHERE PFA_COUNTRY_SETTING_UTILIZATION_VALUE_TYPE.UTILIZATION_VALUE_TYPE_ID =
      ALLOC_REMAP.UTILIZATION_VALUE_TYPE_ID