create table PFA_COUNTRY_SETTING_REVENUE_TYPE_ANALYTIC_SET_LINK (
    COUNTRY_SETTING_REVENUE_TYPE_ID uniqueidentifier,
    ANALYTIC_SET_ID uniqueidentifier,
    primary key (COUNTRY_SETTING_REVENUE_TYPE_ID, ANALYTIC_SET_ID)
);
