alter table PFA_DIRECT_SALE_DETAIL add constraint FK_PFA_DIRECT_SALE_DETAIL_ON_DIRECT_SALE foreign key (DIRECT_SALE_ID) references PFA_DIRECT_SALE(ID);
alter table PFA_DIRECT_SALE_DETAIL add constraint FK_PFA_DIRECT_SALE_DETAIL_ON_PART foreign key (PART_ID) references PN_PART(ID);
create index IDX_PFA_DIRECT_SALE_DETAIL_ON_DIRECT_SALE on PFA_DIRECT_SALE_DETAIL (DIRECT_SALE_ID);
create index IDX_PFA_DIRECT_SALE_DETAIL_ON_PART on PFA_DIRECT_SALE_DETAIL (PART_ID);
