alter table PFA_APPLICATION_DATA add constraint FK_PFA_APPLICATION_DATA_ON_COUNTRY foreign key (COUNTRY_ID) references COUNTRY_COUNTRY(ID);
create index IDX_PFA_APPLICATION_DATA_ON_COUNTRY on PFA_APPLICATION_DATA (COUNTRY_ID);
