alter table PFA_EQUIPMENT_UTILIZATION add constraint FK_PFA_EQUIPMENT_UTILIZATION_ON_COUNTRY foreign key (COUNTRY_ID) references COUNTRY_COUNTRY(ID);
create index IDX_PFA_EQUIPMENT_UTILIZATION_ON_COUNTRY on PFA_EQUIPMENT_UTILIZATION (COUNTRY_ID);
