CREATE OR ALTER VIEW SETTING_UTILIZATION_VALUE_TYPE_vw as
SELECT PCSUVT.UTILIZATION_VALUE_TYPE_ID,
       PCS.COUNTRY_ID,
       PCSUVT.ORDER_
FROM PFA_COUNTRY_SETTING PCS
         JOIN PFA_COUNTRY_SETTING_UTILIZATION_VALUE_TYPE PCSUVT ON PCS.ID = PCSUVT.COUNTRY_SETTING_ID