alter table PFA_ACCOUNT_REVISION add constraint FK_PFA_ACCOUNT_REVISION_ON_MANAGER foreign key (MANAGER_ID) references SEC_USER(ID);
alter table PFA_ACCOUNT_REVISION add constraint FK_PFA_ACCOUNT_REVISION_ON_ACCOUNT foreign key (ACCOUNT_ID) references PFA_ACCOUNT(ID);
create index IDX_PFA_ACCOUNT_REVISION_ON_MANAGER on PFA_ACCOUNT_REVISION (MANAGER_ID);
create index IDX_PFA_ACCOUNT_REVISION_ON_ACCOUNT on PFA_ACCOUNT_REVISION (ACCOUNT_ID);
