alter table PFA_PRICE_LIST_DETAIL add constraint FK_PFA_PRICE_LIST_DETAIL_ON_PRICE_LIST foreign key (PRICE_LIST_ID) references PFA_PRICE_LIST(ID);
alter table PFA_PRICE_LIST_DETAIL add constraint FK_PFA_PRICE_LIST_DETAIL_ON_ANALYTIC foreign key (ANALYTIC_ID) references PFA_ANALYTIC_SET(ID);
alter table PFA_PRICE_LIST_DETAIL add constraint FK_PFA_PRICE_LIST_DETAIL_ON_REVENUE_TYPE foreign key (REVENUE_TYPE_ID) references PFA_REVENUE_TYPE(ID);
create index IDX_PFA_PRICE_LIST_DETAIL_ON_PRICE_LIST on PFA_PRICE_LIST_DETAIL (PRICE_LIST_ID);
create index IDX_PFA_PRICE_LIST_DETAIL_ON_ANALYTIC on PFA_PRICE_LIST_DETAIL (ANALYTIC_ID);
create index IDX_PFA_PRICE_LIST_DETAIL_ON_REVENUE_TYPE on PFA_PRICE_LIST_DETAIL (REVENUE_TYPE_ID);
