alter table PFA_ACTIVITY_DETAIL add constraint FK_PFA_ACTIVITY_DETAIL_ON_ANALYTIC foreign key (ANALYTIC_ID) references PFA_ANALYTIC_SET(ID);
create index IDX_PFA_ACTIVITY_DETAIL_ON_ANALYTIC on PFA_ACTIVITY_DETAIL (ANALYTIC_ID);
