alter table PFA_ACTIVITY_DETAIL add constraint FK_PFA_ACTIVITY_DETAIL_ON_ACTIVITY foreign key (ACTIVITY_ID) references PFA_ACTIVITY(ID);
create index IDX_PFA_ACTIVITY_DETAIL_ON_ACTIVITY on PFA_ACTIVITY_DETAIL (ACTIVITY_ID);
