alter table PFA_ACCOUNT add constraint FK_PFA_ACCOUNT_ON_ACTUAL_MARKET_DETAIL foreign key (ACTUAL_MARKET_DETAIL_ID) references PFA_MARKET_DATA(ID);
create index IDX_PFA_ACCOUNT_ON_ACTUAL_MARKET_DETAIL on PFA_ACCOUNT (ACTUAL_MARKET_DETAIL_ID);
