alter table PFA_ACCOUNT add constraint FK_PFA_ACCOUNT_ON_ACTUAL_REVISION foreign key (ACTUAL_REVISION_ID) references PFA_ACCOUNT_REVISION(ID);
create index IDX_PFA_ACCOUNT_ON_ACTUAL_REVISION on PFA_ACCOUNT (ACTUAL_REVISION_ID);
