exec sp_rename 'PFA_ACTIVITY_DETAIL.WELL_TAG', 'WELL_TAG__U19968', 'COLUMN' ^
exec sp_rename 'PFA_ACTIVITY_DETAIL.WELL_EQUIP', 'WELL_EQUIP__U86394', 'COLUMN' ^
exec sp_rename 'PFA_ACTIVITY_DETAIL.JOB_TYPE', 'JOB_TYPE__U40614', 'COLUMN' ^
exec sp_rename 'PFA_ACTIVITY_DETAIL.CONTRACT_TYPE', 'CONTRACT_TYPE__U99582', 'COLUMN' ^
