alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_SEAL_MATERIALS foreign key (SEAL_MATERIALS_ID) references PFA_MATERIALS(ID);
create index IDX_PFA_SYSTEM_STD_ON_SEAL_MATERIALS on PFA_SYSTEM_STD (SEAL_MATERIALS_ID);
