alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_PUMP_MATERIALS foreign key (PUMP_MATERIALS_ID) references PFA_MATERIALS(ID);
create index IDX_PFA_SYSTEM_STD_ON_PUMP_MATERIALS on PFA_SYSTEM_STD (PUMP_MATERIALS_ID);
