alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_PUMP_TYPE foreign key (PUMP_TYPE_ID) references PFA_PUMP_TYPE(ID);
create index IDX_PFA_SYSTEM_STD_ON_PUMP_TYPE on PFA_SYSTEM_STD (PUMP_TYPE_ID);
