alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_VAPRO_CONFIG foreign key (VAPRO_CONFIG_ID) references PFA_VAPRO_CONFIG(ID);
create index IDX_PFA_SYSTEM_STD_ON_VAPRO_CONFIG on PFA_SYSTEM_STD (VAPRO_CONFIG_ID);
