UPDATE ACC
SET ACC.[APPLICATION_TYPE] = MD.APPLICATION_TYPE__U05268
  ,ACC.[CONTRACT_TYPE] = MD.CONTRACT_TYPE__U41090
    FROM [dbo].[PFA_ACCOUNT] AS ACC
JOIN [dbo].[PFA_MARKET_DATA] MD ON MD.[ACCOUNT_ID] = ACC.ID^