alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_MOTOR_MATERIALS foreign key (MOTOR_MATERIALS_ID) references PFA_MATERIALS(ID);
create index IDX_PFA_SYSTEM_STD_ON_MOTOR_MATERIALS on PFA_SYSTEM_STD (MOTOR_MATERIALS_ID);
