alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_PUMP_CONFIG foreign key (PUMP_CONFIG_ID) references PFA_PUMP_CONFIG(ID);
create index IDX_PFA_SYSTEM_STD_ON_PUMP_CONFIG on PFA_SYSTEM_STD (PUMP_CONFIG_ID);
