alter table PFA_EQUIPMENT_UTILIZATION drop column EQUIPMENT_TYPE_ID__U60828 ;
alter table PFA_EQUIPMENT_UTILIZATION drop column FIRST_RUN_VALUE__U58855 ;
alter table PFA_EQUIPMENT_UTILIZATION drop column SEQUENT_RUN_VALUE__U85517 ;
alter table PFA_EQUIPMENT_UTILIZATION drop column APPLICATION_DATA_ID__U04038 ;
alter table PFA_EQUIPMENT_UTILIZATION drop column REVENUE_MODE__U09775 ;
alter table PFA_EQUIPMENT_UTILIZATION drop column ORDER___U79541 ;
