alter table PFA_ACCOUNT_REVISION add constraint FK_PFA_ACCOUNT_REVISION_ON_MANAGER foreign key (MANAGER_ID) references PFA_EMPLOYEE(ID);
create index IDX_PFA_ACCOUNT_REVISION_ON_MANAGER on PFA_ACCOUNT_REVISION (MANAGER_ID);
