alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_INTAKE_CONFIG foreign key (INTAKE_CONFIG_ID) references PFA_INTAKE_CONFIG(ID);
create index IDX_PFA_SYSTEM_STD_ON_INTAKE_CONFIG on PFA_SYSTEM_STD (INTAKE_CONFIG_ID);
