exec sp_rename 'PFA_EQUIPMENT_UTILIZATION.ORDER_', 'ORDER___U79541', 'COLUMN' ^
exec sp_rename 'PFA_EQUIPMENT_UTILIZATION.REVENUE_MODE', 'REVENUE_MODE__U09775', 'COLUMN' ^
exec sp_rename 'PFA_EQUIPMENT_UTILIZATION.APPLICATION_DATA_ID', 'APPLICATION_DATA_ID__U04038', 'COLUMN' ^
alter table PFA_EQUIPMENT_UTILIZATION alter column APPLICATION_DATA_ID__U04038 uniqueidentifier  ;
alter table PFA_EQUIPMENT_UTILIZATION drop constraint FK_PFA_EQUIPMENT_UTILIZATION_ON_APPLICATION_DATA ;
drop index IDX_PFA_EQUIPMENT_UTILIZATION_ON_APPLICATION_DATA on PFA_EQUIPMENT_UTILIZATION ;
exec sp_rename 'PFA_EQUIPMENT_UTILIZATION.SEQUENT_RUN_VALUE', 'SEQUENT_RUN_VALUE__U85517', 'COLUMN' ^
exec sp_rename 'PFA_EQUIPMENT_UTILIZATION.FIRST_RUN_VALUE', 'FIRST_RUN_VALUE__U58855', 'COLUMN' ^
exec sp_rename 'PFA_EQUIPMENT_UTILIZATION.EQUIPMENT_TYPE_ID', 'EQUIPMENT_TYPE_ID__U60828', 'COLUMN' ^
alter table PFA_EQUIPMENT_UTILIZATION drop constraint FK_PFA_EQUIPMENT_UTILIZATION_ON_EQUIPMENT_TYPE ;
drop index IDX_PFA_EQUIPMENT_UTILIZATION_ON_EQUIPMENT_TYPE on PFA_EQUIPMENT_UTILIZATION ;
alter table PFA_EQUIPMENT_UTILIZATION add YEAR_ integer ;
alter table PFA_EQUIPMENT_UTILIZATION add MONTH_ integer ;
alter table PFA_EQUIPMENT_UTILIZATION add RECORD_TYPE nvarchar(50) ;
alter table PFA_EQUIPMENT_UTILIZATION add VALID_FROM datetime2 ;
alter table PFA_EQUIPMENT_UTILIZATION add ACCOUNT_ID uniqueidentifier ;
