exec sp_rename 'PFA_ACCOUNT_REVISION.MANAGER_ID', 'MANAGER_ID__U28475', 'COLUMN' ^
alter table PFA_ACCOUNT_REVISION drop constraint FK_PFA_ACCOUNT_REVISION_ON_MANAGER ;
drop index IDX_PFA_ACCOUNT_REVISION_ON_MANAGER on PFA_ACCOUNT_REVISION ;
alter table PFA_ACCOUNT_REVISION add MANAGER_ID uniqueidentifier ;
