alter table PFA_SYSTEM_STD add constraint FK_PFA_SYSTEM_STD_ON_SEAL_CONFIG foreign key (SEAL_CONFIG_ID) references PFA_SEAL_CONFIG(ID);
create index IDX_PFA_SYSTEM_STD_ON_SEAL_CONFIG on PFA_SYSTEM_STD (SEAL_CONFIG_ID);
