WITH
    REVTYPE AS (
        SELECT
            PLD.PRICE_LIST_ID
             ,PLD.VALUE_
             ,RT.NAME
             ,ROW_NUMBER() OVER(PARTITION BY PLD.PRICE_LIST_ID ORDER BY PLD.PRICE_LIST_ID) AS RNUM
        FROM PFA_PRICE_LIST_DETAIL PLD
                 JOIN PFA_REVENUE_TYPE RT ON RT.ID = PLD.REVENUE_TYPE_ID AND RT.NAME = 'RR'
    ),
    FIRSTREVTYPE AS (
        SELECT *
        FROM REVTYPE
        WHERE RNUM = 1
    )
UPDATE PFA_PRICE_LIST
SET RENTAL_RATE = FIRSTREVTYPE.VALUE_
    FROM FIRSTREVTYPE
WHERE FIRSTREVTYPE.PRICE_LIST_ID = PFA_PRICE_LIST.ID^

WITH
    REVTYPE AS (
    SELECT
    PLD.PRICE_LIST_ID
        ,PLD.VALUE_
        ,RT.NAME
        ,ROW_NUMBER() OVER(PARTITION BY PLD.PRICE_LIST_ID ORDER BY PLD.PRICE_LIST_ID) AS RNUM
    FROM PFA_PRICE_LIST_DETAIL PLD
    JOIN PFA_REVENUE_TYPE RT ON RT.ID = PLD.REVENUE_TYPE_ID AND RT.NAME = 'RM'
    ),
    FIRSTREVTYPE AS (
    SELECT *
    FROM REVTYPE
    WHERE RNUM = 1
    )
UPDATE PFA_PRICE_LIST
SET REMOTE_MONITORING = FIRSTREVTYPE.VALUE_
    FROM FIRSTREVTYPE
WHERE FIRSTREVTYPE.PRICE_LIST_ID = PFA_PRICE_LIST.ID^

WITH
    REVTYPE AS (
    SELECT
    PLD.PRICE_LIST_ID
        ,PLD.VALUE_
        ,RT.NAME
        ,ROW_NUMBER() OVER(PARTITION BY PLD.PRICE_LIST_ID ORDER BY PLD.PRICE_LIST_ID) AS RNUM
    FROM PFA_PRICE_LIST_DETAIL PLD
    JOIN PFA_REVENUE_TYPE RT ON RT.ID = PLD.REVENUE_TYPE_ID AND RT.NAME = 'WCk'
    ),
    FIRSTREVTYPE AS (
    SELECT *
    FROM REVTYPE
    WHERE RNUM = 1
    )
UPDATE PFA_PRICE_LIST
SET WELL_CHECK = FIRSTREVTYPE.VALUE_
    FROM FIRSTREVTYPE
WHERE FIRSTREVTYPE.PRICE_LIST_ID = PFA_PRICE_LIST.ID^
